import tempfile
import time

import click
import numpy as np
from mujoco._structs import MjModel
from stretch4_urdf import get_urdf

import stretch4_mujoco.utils as utils
from stretch4_mujoco.datamodels.status_command import CommandBaseVelocity
from stretch4_mujoco.datamodels.status_stretch_camera import StatusStretchCameras
from stretch4_mujoco.enums.actuators import Actuators
from stretch4_mujoco.enums.stretch_cameras import StretchCameras
from stretch4_mujoco.stretch_mujoco_simulator import StretchMujocoSimulator
from stretch4_mujoco.utils import block_until_check_succeeds, require_connection

from stretch4_mujoco.utils import URDFmodel


class Stretch4MujocoSimulator(StretchMujocoSimulator):
    """
    Stretch Mujoco Simulator class for interfacing with the Mujoco Server.

    Calling `start()` will spawn a new process that runs `MujocoServer` and the simulator.

    You can specify `start(headless=True)` to run the simulation without a GUI.

    Data from the MujocoServer is sent to StretchMujocoSimulator using proxies.

    Use `pull_status()` and `pull_camera_data()` to access simulation data.
    """

    def __init__(
        self,
        scene_xml_path: str | None = None,
        model: MjModel | None = None,
        camera_hz: float = 30,
        cameras_to_use: list[StretchCameras] = [],
        start_translation: list | None = None,
        start_rotation_quat: list | None = None,
        use_full_center_camera_resolution: bool = False,
    ) -> None:
        # Dynamically generate the MJCF so it's ready for any scene that includes it
        self.get_robot_xml_path()

        if model is None and scene_xml_path is None:
            # if no scene or model is provided, use the se4 default
            scene_xml_path = self.get_scene_xml_path()

        if not cameras_to_use:
            cameras_to_use = self.get_all_cameras()

        if not use_full_center_camera_resolution:
            cameras_to_use = [
                StretchCameras.cam_nav_rgb_se4_center_low_rez
                if cam == StretchCameras.cam_nav_rgb_se4_center
                else cam
                for cam in cameras_to_use
            ]

        super().__init__(
            scene_xml_path=scene_xml_path,
            model=model,
            camera_hz=camera_hz,
            cameras_to_use=cameras_to_use,
            start_translation=start_translation,
            start_rotation_quat=start_rotation_quat,
        )


        urdf_model = URDFmodel(Stretch4MujocoSimulator.get_urdf_path())
        joint_positions = {
            "wrist_yaw": 0.0,
            "wrist_pitch": 0.0,
            "wrist_roll": 0.0,
            "lift": 0.0,
            "arm": 0.0,
            "head_pan": 0.0,
            "head_tilt": 0.0,
        }

        self.T_base_left = urdf_model.get_transform(joint_positions, "lidar_left_link")
        self.T_base_right = urdf_model.get_transform(joint_positions, "lidar_right_link")

    @staticmethod
    def get_scene_xml_path() -> str:
        """
        Returns the default scene XML path for the Stretch Mujoco Simulator.
        """
        return str(utils.models_path / "scene_stretch4.xml")

    @staticmethod
    def get_robot_xml_path() -> str:
        """
        Returns the default robot XML path for the Stretch Mujoco Simulator.
        """
        from stretch4_mujoco.models.stretch_4.mjcf_generator import generate_mjcf

        urdf_path = Stretch4MujocoSimulator.get_urdf_path()

        # Paths for dynamic generation
        raw_mjcf_path = str(utils.models_path / "stretch_4" / "autogenerated_stretch_4_model.xml")
        dynamic_xml_path = str(utils.models_path / "stretch_4" / "stretch_4_dynamic.xml")

        generate_mjcf(urdf_path, raw_mjcf_path)

        # Create wrapper XML that includes the generated MJCF
        wrapper_xml = f"""<mujoco model="stretch_4">
  <include file="defaults.xml"/>
  <include file="autogenerated_stretch_4_model.xml"/>
  <include file="contact.xml"/>
  <include file="autogenerated_actuator_sensor.xml"/>
  <include file="keyframes.xml"/>
</mujoco>"""

        with open(dynamic_xml_path, "w") as f:
            f.write(wrapper_xml)

        return utils.get_absolute_path_stretch_xml(dynamic_xml_path)

    @staticmethod
    def get_default_model_batch_tool_names() -> tuple[str, str, str]:
        return "SE4", "francis", "eoa_wrist_dw4_tool_sg4"

    @staticmethod
    def get_urdf_path() -> str:
        model_name, batch_name, tool_name = (
            Stretch4MujocoSimulator.get_default_model_batch_tool_names()
        )

        out_dir = tempfile.mkdtemp()
        generated_urdf_path = get_urdf(
            model_name=model_name,
            batch_name=batch_name,
            tool_name=tool_name,
            output_dir=out_dir,
            description="mujoco_stretch_4",
        )
        print(f"Generated URDF path: {generated_urdf_path}")
        return generated_urdf_path

    @staticmethod
    def get_all_cameras() -> list[StretchCameras]:
        return StretchCameras.all_stretch4()

    @staticmethod
    def get_rgb_cameras() -> list[StretchCameras]:
        return StretchCameras.rgb_stretch4()

    def pull_camera_data(self) -> StatusStretchCameras:
        data = super().pull_camera_data()
        if data.cam_nav_rgb_se4_center_low_rez is not None:
            data.cam_nav_rgb_se4_center = data.cam_nav_rgb_se4_center_low_rez
            data.cam_nav_rgb_se4_center_low_rez = None
        return data

    def is_reached_set_position(self, actuator: str | Actuators, position_tolerance: float = 0.05):
        """
        Checks if the joint has reached a previously commanded location.

        Only listens to the `move_to` command.
        """
        if isinstance(actuator, str):
            actuator = Actuators[actuator]

        if actuator in [
            Actuators.base_rotate,
            Actuators.base_translate,
            Actuators.left_wheel_vel,
            Actuators.right_wheel_vel,
            Actuators.back_wheel_vel,
        ]:
            raise NotImplementedError(f"Check joint reached is not supported for {actuator}.")

        return super().is_reached_set_position(
            actuator=actuator, position_tolerance=position_tolerance
        )

    def wait_while_is_moving(
        self,
        actuator: str | Actuators,
        timeout: float | None = 5.0,
        check_interval: float = 0.1,
        position_tolerance: float = 0.0005,
    ):
        """
        Checks position after a delay, and blocks if position has changed.
        If `timeout` is None, will block indefinitely.
        """
        if isinstance(actuator, str):
            actuator = Actuators[actuator]

        def check_if_moved():
            """Checks movement, returns True if movement is detected."""
            time.sleep(check_interval)

            if actuator in [
                Actuators.left_wheel_vel,
                Actuators.right_wheel_vel,
                Actuators.back_wheel_vel,
                Actuators.base_rotate,
                Actuators.base_translate,
            ]:
                current_position = actuator.get_position_relative(self.pull_status())
                if actuator == Actuators.left_wheel_vel or actuator == Actuators.base_translate:
                    current_position = current_position[0]
                elif actuator == Actuators.right_wheel_vel:
                    current_position = current_position[1]
                elif actuator == Actuators.back_wheel_vel:
                    current_position = current_position[0]
                elif actuator == Actuators.base_rotate:
                    current_position = current_position[2]
            else:
                current_position = actuator.get_position(self.pull_status())

            if not actuator in self._last_movement_positions:
                self._last_movement_positions[actuator] = current_position
                return True

            last_position = self._last_movement_positions[actuator]

            is_moved = not np.isclose(current_position, last_position, atol=position_tolerance)

            self._last_movement_positions[actuator] = current_position

            return is_moved

        if not block_until_check_succeeds(
            wait_timeout=timeout,
            check=lambda: check_if_moved() == False,
            is_alive=self.is_running,
            time_fn=lambda: self.pull_status().time,
        ):
            if timeout is not None:
                click.secho(
                    f"Timeout: Joint {actuator.name} is still moving after {timeout}.",
                    fg="red",
                )
            return False
        return True

    @require_connection
    def _move_to(self, actuator: str | Actuators, pos: float) -> None:
        """
        Move the actuator to an absolute position.
        Args:
            actuator: string name of the actuator or Actuator enum instance
            pos: float, absolute position goal

        Use `wait_until_at_setpoint()` or `wait_while_is_moving()` to block until the joint reaches its location.
        """
        if isinstance(actuator, str):
            actuator = Actuators[actuator]

        if actuator in [
            Actuators.left_wheel_vel,
            Actuators.right_wheel_vel,
            Actuators.back_wheel_vel,
            Actuators.base_rotate,
            Actuators.base_translate,
        ]:
            raise Exception(
                f"Cannot set an absolute position for a continuous joint {actuator.name}"
            )
        return super()._move_to(actuator=actuator, pos=pos)

    @require_connection
    def _move_by(self, actuator: str | Actuators, pos: float):
        """
        Move the actuator by a relative amount.
        Args:
            actuator: string name of the actuator or Actuator enum instance
            pos: float, position to increment by

        Use `wait_until_at_setpoint()` or `wait_while_is_moving()` to block until the joint reaches its location.
        """
        if isinstance(actuator, str):
            actuator = Actuators[actuator]

        if actuator in [
            Actuators.left_wheel_vel,
            Actuators.right_wheel_vel,
            Actuators.back_wheel_vel,
        ]:
            click.secho(
                f"Cannot set a position for a velocity joint {actuator.name}",
                fg="red",
            )
            raise Exception(
                f"Cannot set an absolute position for a continuous joint {actuator.name}"
            )

        return super()._move_by(actuator=actuator, pos=pos)

    @require_connection
    def _set_base_velocity(self, v_x: float, v_y: float, omega: float) -> None:
        """
        Set the base velocity of the robot
        Args:
            v_x: float, linear velocity
            v_y: float, linear velocity
            omega: float, angular velocity
        """

        with self._command_lock:
            command = self.data_proxies.get_command()
            command.set_base_velocity(
                CommandBaseVelocity(v_x=v_x, v_y=v_y, omega=omega, trigger=True)
            )


            self.data_proxies.set_command(command)

    @require_connection
    def pull_hemi_lidar_points(self) -> dict[str, np.ndarray]:
        """
        Traces rays and computes point clouds from the simulated lidars.
        """
        return self.data_proxies.get_hesai_lidar_points()

    @require_connection
    def pull_hesai_lidar_points(self) -> dict[str, np.ndarray]:
        """
        Traces rays and computes point clouds from the simulated lidars.
        """
        return self.data_proxies.get_hesai_lidar_points()
