[project]
name = "stretch4_mujoco"
# Versioning follow CalVer (YYYY.MM.DD) for PEP 440 compliance
version = "2026.05.07"
description = "A Stretch 4 simulation in MuJoCo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hello-robot-stretch4-urdf>=2026.5.6",
    "mujoco==3.3.1",
    "yourdfpy",
    "urdf2mjcf>=0.2.39"

]
authors = [
    {name = "Hello Robot Inc.", email = "support@hello-robot.com"},
]
license = { file = "LICENSE"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
]

[project.optional-dependencies]
tools = ["matplotlib>=3.10.1", "inputs>=0.5", "click>=8.1.8", "pynput>=1.8.1", "rerun-sdk>=0.23.1", "opencv-python"]
dev = [
    "pre-commit",
    "pytest",
    "flake8",
    "black",
    "mypy",
]
jupyter = [
    "ipykernel",
    "ipython",
]

[tool.setuptools.packages.find]
exclude = ["third_party*", "tests*"]

[project.urls]
Source = "https://github.com/hello-robot/stretch4_mujoco"
Tracker = "https://github.com/hello-robot/stretch4_mujoco/issues"

[tool.black]
line-length = 100
